# Generated by Django 6.0.1 on 2026-01-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20260113_1412'),
    ]

    operations = [
    ]
