# Generated by Django 6.0.1 on 2026-01-24 03:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BplanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='bplan', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.bplan_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='business', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.business_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetxRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='detx', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.detx_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPRRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='ipr', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.ipr_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='product', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.product_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RisingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='rising', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.rising_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='startup', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.startup_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StocksRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='stocks', max_length=50)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_roll', models.CharField(max_length=50)),
                ('lead_department', models.CharField(max_length=50)),
                ('lead_year', models.CharField(max_length=10)),
                ('lead_mobile', models.CharField(max_length=20)),
                ('lead_email', models.EmailField(max_length=254)),
                ('payment_screenshots', models.FileField(blank=True, null=True, upload_to=app.models.stocks_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
