# Generated by Django 6.0.1 on 2026-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bplanregistration_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchregistration',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchregistration',
            name='mail_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitchregistration',
            name='mail_sent_subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
